"""migrate

Revision ID: d1ce30796b4c
Revises: 
Create Date: 2023-05-10 13:10:53.454651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ce30796b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('what_youre_bringing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top', sa.String(), nullable=True),
    sa.Column('bottom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_what_youre_bringing'))
    )
    op.create_table('our_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doer_id', sa.Integer(), nullable=True),
    sa.Column('bringing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bringing_id'], ['what_youre_bringing.id'], name=op.f('fk_our_recommendations_bringing_id_what_youre_bringing')),
    sa.ForeignKeyConstraint(['doer_id'], ['users.id'], name=op.f('fk_our_recommendations_doer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_our_recommendations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('our_recommendations')
    op.drop_table('what_youre_bringing')
    op.drop_table('users')
    # ### end Alembic commands ###
